### PR TITLE
fix(react-native): async storage bad import warning

### PR DESCRIPTION
**Pull request by pedpess**
Fixes https://github.com/avohq/js-avo-inspector/issues/91

### CODE REVIEW

**Comment by hugihlynsson** [comment]
Nice! This looks good. Since this is requiring a new package, do you want to add `yarn add @react-native-async-storage/async-storage` to get the dependency into the to package.json a'la https://react-native-async-storage.github.io/async-storage/docs/install/ ?

**Comment by pedpess** [comment]
Ah, good point, but where do I add this package? To `"externals": ["react-native", "@react-native-async-storage/async-storage"]` in `package.json` located in the root level of the repository?

**Comment by logason** [comment]
Thank you for this PR @pedpess 🙌 

> Ah, good point, but where do I add this package? To `"externals": ["react-native", "@react-native-async-storage/async-storage"]` in `package.json` located in the root level of the repository?

It looks like we don't have any dependencies at this moment, so this would be the first one. Doing `yarn add -E @react-native-async-storage/async-storage` in the root should update `package.json` correctly (add a "dependencies" key).

Let us know if that doesn't work out, or if you want us to take it from here.

**Comment by pedpess** [comment]
Hi @logason 👋🏻 , I have just added the new depen here [6ebcb19](https://github.com/avohq/js-avo-inspector/pull/92/commits/6ebcb19c7337f14cc64855b58ebbfc830b9bdeb9). Thanks for the guidance

**Comment by alex-tpom6oh** [comment]
Thanks @pedpess, taking this forward in #93

**Pull request closed without merging**
